version: "3"

services:
  nbot:
    restart: unless-stopped
    build: .
    ports:
      - "6667:6667"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    external:
      name: nbot-mongodb
